# Generated by Django 5.0.14 on 2026-04-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Marque')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Option')),
                ('icon', models.CharField(blank=True, help_text='Icon class (e.g., fas fa-snowflake)', max_length=50)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilométrage')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], default='petrol', max_length=20, verbose_name='Carburant')),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique'), ('semi_auto', 'Semi-automatique')], default='manual', max_length=20, verbose_name='Transmission')),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance (ch)')),
                ('engine_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Cylindrée (L)')),
                ('drivetrain', models.CharField(choices=[('fwd', 'Traction avant'), ('rwd', 'Propulsion'), ('awd', 'Intégrale'), ('4wd', '4x4')], default='fwd', max_length=10, verbose_name='Transmission')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Couleur')),
                ('doors', models.PositiveIntegerField(default=4, verbose_name='Portes')),
                ('seats', models.PositiveIntegerField(default=5, verbose_name='Places')),
                ('condition', models.CharField(choices=[('new', 'Neuf'), ('excellent', 'Excellent'), ('good', 'Bon état'), ('fair', 'État correct')], default='excellent', max_length=20, verbose_name='État')),
                ('vin_number', models.CharField(blank=True, max_length=17, verbose_name='N° de série')),
                ('registration_city', models.CharField(blank=True, max_length=50, verbose_name="Ville d'immatriculation")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (MAD)')),
                ('negotiable_price', models.BooleanField(default=False, verbose_name='Prix négociable')),
                ('featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservée'), ('sold', 'Vendue')], default='available', max_length=20, verbose_name='Statut')),
                ('published', models.BooleanField(default=True, verbose_name='Publiée')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.brand', verbose_name='Marque')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.category', verbose_name='Catégorie')),
                ('features', models.ManyToManyField(blank=True, related_name='cars', to='cars.feature', verbose_name='Options')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='cars/%Y/%m/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order', '-is_featured', 'created_at'],
            },
        ),
    ]
