# Generated by Django 5.0.14 on 2026-04-22 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AutoMaroc', max_length=100)),
                ('site_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('site_logo', models.ImageField(blank=True, help_text='Site logo (recommended: 200x60px)', null=True, upload_to='site/')),
                ('site_favicon', models.ImageField(blank=True, help_text='Favicon (recommended: 32x32px or 64x64px)', null=True, upload_to='site/')),
                ('site_email', models.EmailField(blank=True, help_text='Contact email address', max_length=255)),
                ('site_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('site_address', models.TextField(blank=True, help_text='Physical address')),
                ('footer_text', models.TextField(blank=True, help_text='Copyright text or footer message')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', validators=[django.core.validators.URLValidator()])),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', validators=[django.core.validators.URLValidator()])),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL', validators=[django.core.validators.URLValidator()])),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL', validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn page URL', validators=[django.core.validators.URLValidator()])),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number (e.g., +212600000000)', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System Preference)')], default='light', help_text='Default site theme', max_length=10)),
                ('primary_color', models.CharField(default='#111827', help_text='Primary brand color (hex)', max_length=7)),
                ('accent_color', models.CharField(default='#DC2626', help_text='Accent color (hex)', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
